sudo: false
dist: trusty
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  fast_finish: true

  # Remove before UF 4.4.0 official release, and after 7.4 release !
  allow_failures:
    - php: 7.4snapshot
    
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
